### ISSUE TITLE
Use Nite and Virtual Device without a kinect.

### ISSUE THREAD

**Issue by pedropva** [VIML/VirtualDeviceForOpenNI2#1]
Hi, im trying to figure out a way of getting skeleton data from a point cloud using Nite, but im having troubles adapting your Nite Sample to my purpose:
In Nite Sample you use a Kinect's Depth Stream and copy its properties and data to the Virtual Stream, but every time i try to simulate the properties to run it  without directly copying the properties directly from the Kinect i get this error:
![couldnt allocate m_pshifttodepth buffer](https://user-images.githubusercontent.com/20668173/38195647-de9ff7ec-3654-11e8-8a6e-a9b5b5ffbee5.png)

What i really want is to know if its possible to use Nite to identify a skeleton from point cloud data (which is in a file) whithout having a kinect attached to it, just the virtual device.

Here is my code:
[Pedropva's_NiTESample.zip](https://github.com/VIML/VirtualDeviceForOpenNI2/files/1868042/Pedropva.s_NiTESample.zip)

Im looking forward to any advice and thanks for your attention.

**Comment by VIML** [comment]
The license of NiTE does not allow user to run it without PrimeSense Sensor connected.

**Comment by pedropva** [comment]
Thanks for the quick reply, but even if i got to have Kinect attached is it possible to get the skeleton tracking with the overwriting the Kinect's data with the data from my file?
