### ISSUE TITLE
Nite isnt working with virtual device and kinect

### ISSUE THREAD

**Issue by pedropva** [VIML/VirtualDeviceForOpenNI2#2]
Hi, im new to OpenNi and Nite and im trying to test if i can enhance kinect's data before using it on Nite but i just cant get VirtualDevice to work with kinect. I cut out all the OpenCV lines because i was having troubles getting that version, so i would be able to use the Nite Sample but without visualization.
I just want to know if Nite can identify a person in the frame or not, but i cant get it to work,It works  perfectly fine if i initialize Nite with the kinect Device , but if i switch out to virtualDevice it runs but it doesnt detect if im in the frame or not.

![with_kinectdevice](https://user-images.githubusercontent.com/20668173/38679002-fad99f94-3e38-11e8-81d8-5c17660da51e.png)

![with_virtualdevice](https://user-images.githubusercontent.com/20668173/38679003-faf40ea6-3e38-11e8-8312-2f2d8f423001.png)

I know the virtualDevice is getting the data from kinect because if i put my finger infront of the sensor the depth data becomes 0 and if i take it of the data becomes different than zero.

Without my finger in front of the sensor:
![non-zeroes](https://user-images.githubusercontent.com/20668173/38679232-a13b22f4-3e39-11e8-85b8-0254e39d9be3.png)

With my finger in front of the senseor:
![zeroes](https://user-images.githubusercontent.com/20668173/38679233-a1582d7c-3e39-11e8-831a-05d934ae8599.png)

Here are my files:
[Pedropva's_NiTESample.zip](https://github.com/VIML/VirtualDeviceForOpenNI2/files/1903202/Pedropva.s_NiTESample.zip)

Thanks for the attention and sorry for bad english.
EDIT: Sorry, i meant OpenCV.

**Comment by KHeresy** [comment]
There is no OpenGL code in this sample.
The visualize part is using OpenCV.

Please make sure the original sample works first before modify.

**Comment by pedropva** [comment]
I've run the original sample and now i have and idea of why it doesnt work:



When i put my finger in front of the sensor and use the original kinect Frame:
![kinectframe](https://user-images.githubusercontent.com/20668173/38741681-d4756c88-3f10-11e8-8712-34ac054f2726.png)

When i put my finger in front of the sensor and use the Virtual Device Frame:
![virtualframe](https://user-images.githubusercontent.com/20668173/38741667-ca86ccf8-3f10-11e8-8c7b-d2b1238d6143.png)

Obviously the Height and Width of the Frames are different, so i have some questions:
1.Why is that?
2.Can i make the Virtual Device frame bigger?

This might explain why i wasnt getting any people detection at all: 
Because they werent in the frame sent to Nite 😄 
Thanks for your attention.

**Comment by KHeresy** [comment]
I have checked the code.

This should be an error inside virtual device, which set the wrong size.

The source code should had been fixed. 
Please pull the new code and rebuild it.

**Comment by pedropva** [comment]
Ok i got it to work and its all ok now! Thanks for the support!
![sucess](https://user-images.githubusercontent.com/20668173/38866843-92a86bd8-4218-11e8-897f-b6e83fb1f4e6.png)
